global class plannedworksDataCLs
{
/*
global without sharing class Integrations_AnalysP_PlannedW_Data_Cls
    {
    
         global class plannedWorksInformation
        {
            webservice Planned_Works__c plannedWorksObj;
            webservice List<String>  SoldServiceList;
            webservice List<String> FAILED_REASON;
            webservice String Operation_String;  
                         
        global plannedWorksInformation(Planned_Works__c plannedWorksObj,List<String> SoldServiceList)
        {
                this.plannedWorksObj = plannedWorksObj;
                this.SoldServiceList = SoldServiceList; 
        }      
        
        // Empty Constructore
        global plannedWorksInformation(){}
          
    }
    
    public enum Operation {
                            CREATE // Create the invoices in the SFDC system
    }   
    
}

*/

}