global class plannedworksWSCLs
{
/*

global class  Integrations_AnalysP_PlannedW_WS_Cls{ 
    
    global class AnalysPWebServiceCls {
        webservice List<Integrations_AnalysP_PlannedW_Data_Cls.plannedWorksInformation> plannedWorksInformation;
    }
    
   webservice static AnalysPWebServiceCls createWS(AnalysPWebServiceCls planWorkInfo){ 
        AnalysPWebServiceCls AWS = new AnalysPWebServiceCls();
        AWS.plannedWorksInformation =  Integrations_AnalysP_PlannedW_Cls.create(planWorkInfo.plannedWorksInformation); 
        return AWS;     
    } 
}

*/

}